# Generated by Django 4.0.6 on 2022-11-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challengue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deportistas',
            new_name='deportista',
        ),
    ]
