# Generated by Django 4.0.6 on 2022-11-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengue', '0002_rename_deportistas_deportista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='wod_numero',
        ),
        migrations.AddField(
            model_name='deportista',
            name='Categoria',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='Puntos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wod',
            name='Puntos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wod',
            name='Wod_numero',
            field=models.IntegerField(null=True),
        ),
    ]
