# Generated by Django 4.0.6 on 2022-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengue', '0004_deportista_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='w1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='w2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='w3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='w4',
            field=models.IntegerField(null=True),
        ),
    ]
